In [12]:
import math
import numpy as np
from matplotlib import pyplot as plt

In [51]:
# Task Setup
data: np.array = np.random.uniform(low=0.5,high=40,size=(7,4))
sample: np.array = data[:,0]
v1: np.array = data[:,2]

In [52]:
# Task 1 Use the relational operator, <, to test if π is less than 4. Assign the output to a variable named test.
test: int = int(math.pi < 4)
test

1

In [53]:
# Task 2 Test the vector v1 for elements that are less than 4. Assign the output to a variable named test.
test_v1: np.array = v1 < 4
test_v1

array([ True,  True, False, False, False, False, False], dtype=bool)

In [54]:
# Task 3 Create a variable v containing all the elements in v1 that are less than four.
v: np.array = v1[test_v1]
v

array([ 3.45506186,  3.89806135])

In [60]:
s: np.array = sample[test_v1]
s

array([  1.17794163,  25.78563228])

In [63]:
# Task 4 Modify v1 so that any value less than 4 is replaced with the value 0
v1[test_v1] = 0
v1

array([  0.        ,   0.        ,   4.45567396,  23.95347586,
        29.87646641,  32.43856692,  11.30072822])