In [20]:
import numpy as np

In [28]:
data: np.array = np.random.rand(7,4)
data

array([[ 0.53274837,  0.58750664,  0.81983668,  0.58320594],
       [ 0.72129036,  0.00874161,  0.78101154,  0.6251966 ],
       [ 0.51256273,  0.71479953,  0.65829978,  0.92344003],
       [ 0.79378189,  0.79859575,  0.97518288,  0.54465921],
       [ 0.21099852,  0.88310365,  0.99333978,  0.63480664],
       [ 0.67513638,  0.10184794,  0.65787118,  0.46955117],
       [ 0.96747879,  0.96496558,  0.79513158,  0.41480654]])

In [29]:
# Task 1 Create a variable named density that contains the second column of the matrix named data.
density: np.array = data[:,1]
density

array([ 0.58750664,  0.00874161,  0.71479953,  0.79859575,  0.88310365,
        0.10184794,  0.96496558])

In [30]:
# Task 2
# Create a variable volumes containing the last two columns of data.
volumes: np.array = data[:,-2:]
volumes

array([[ 0.81983668,  0.58320594],
       [ 0.78101154,  0.6251966 ],
       [ 0.65829978,  0.92344003],
       [ 0.97518288,  0.54465921],
       [ 0.99333978,  0.63480664],
       [ 0.65787118,  0.46955117],
       [ 0.79513158,  0.41480654]])

In [32]:
# Task 3
# Using a single index value, create a variable named p containing the 6th element in the vector density.
p: float = density[5]
p

0.10184794297178124

In [36]:
# Task 4
# Using a range of index values, create a vector named p containing the 2nd through 5th elements of density.
# p ist schon vergeben, es ist also ein neuer Vektor gesucht. Es wäre ein bad pattern hier die float Variable neu 
# zu initialisieren
# Numpy ist hier inklusiv und Matlab ist exklusiv. Das bedeutet, dass das Ende eines Arrays bei Numpy immer mit
# dem letzte angegebenen Element ist. Daher 2,3,4,5 für [1:5]

v: np.array = density[1:5]
v

array([ 0.00874161,  0.71479953,  0.79859575,  0.88310365])