In [1]:
import numpy as np

In [3]:
data: np.array = np.random.rand(7,4)
data

array([[ 0.97909013,  0.64750553,  0.11178611,  0.4534409 ],
       [ 0.05494392,  0.02830877,  0.78565417,  0.49294221],
       [ 0.59264998,  0.03723322,  0.72146008,  0.12777225],
       [ 0.66177633,  0.86675108,  0.13928995,  0.81232442],
       [ 0.16997179,  0.74674252,  0.7431638 ,  0.68162605],
       [ 0.94984873,  0.28265453,  0.07536441,  0.10795418],
       [ 0.08172722,  0.23333121,  0.72161626,  0.1817966 ]])

In [6]:
# Task 1 Create a vector named v2 containing the last column of data.
v2: np.array = data[:,-1]
v2

array([ 0.4534409 ,  0.49294221,  0.12777225,  0.81232442,  0.68162605,
        0.10795418,  0.1817966 ])

In [9]:
# Task 2 Change the first element in v2 from NaN to 0.5.
v2[0] = 0.5
v2[0]

0.5

In [14]:
# Task 3 Change the value of the element in the first row and last column of data to 0.5.
data[0,-1] = 0.5
data

array([[ 0.97909013,  0.64750553,  0.11178611,  0.5       ],
       [ 0.05494392,  0.02830877,  0.78565417,  0.49294221],
       [ 0.59264998,  0.03723322,  0.72146008,  0.12777225],
       [ 0.66177633,  0.86675108,  0.13928995,  0.81232442],
       [ 0.16997179,  0.74674252,  0.7431638 ,  0.68162605],
       [ 0.94984873,  0.28265453,  0.07536441,  0.10795418],
       [ 0.08172722,  0.23333121,  0.72161626,  0.1817966 ]])