In [1]:
import numpy as np

In [7]:
# Task Setup
data: np.array = np.random.rand(7,4)
density: np.array = data[:,1]
v1: np.array = data[:,2]
v2: np.array = data[:,3]

array([ 0.17253516,  0.70285413,  0.98295764,  0.20966086,  0.59204517,
        0.2114799 ,  0.42040048])

In [15]:
# Task 1 Add 1 to each element of v1 and store the result in a variable named r.
r: np.array = v1 + 1
r

array([ 7.51601443,  7.20062015,  7.38158122,  7.88443719,  7.45926375,
        7.31891827,  7.59242748])

In [18]:
# Task 2 Create a vector vs that is the sum of the vectors v1 and v2.
vs: np.array = v1 + v2
vs

array([ 6.68854959,  6.90347428,  7.36453886,  7.09409805,  7.05130893,
        6.53039818,  7.01282796])

In [20]:
# Task 3 Create a variable va that contains the value vs divided by 2 (the average volume).
va: np.array = vs / 2
va

array([ 3.3442748 ,  3.45173714,  3.68226943,  3.54704902,  3.52565446,
        3.26519909,  3.50641398])

In [23]:
# Task 4 Create a variable vm containing the maximum of the va vector.
vm: float = np.max(va)
vm

3.68226942909198

In [25]:
# Task 5 Using the round function, create a variable named vr which contains the rounded average volumes, va.
va: np.array = np.round(va)
va

array([ 3.,  3.,  4.,  4.,  4.,  3.,  4.])

In [35]:
# Task 5 Create a variable named mass containing the elementwise product of density and va.
mass: np.array = np.multiply(density, va)
mass
# oder simpel mass = density * va

array([ 2.35693185,  2.52321772,  3.3638483 ,  2.57285494,  2.93590846,
        0.2702422 ,  3.49150779])